//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_chave
    {
        public int cdChave { get; set; }
        public int cdFabricante { get; set; }
        public int cdSoftware { get; set; }
        public int cdTecnologia { get; set; }
        public string chave { get; set; }
        public string licenca { get; set; }
        public int deleted { get; set; }
    
        public virtual tb_fabricante tb_fabricante { get; set; }
        public virtual tb_software tb_software { get; set; }
        public virtual tb_tecnologia tb_tecnologia { get; set; }
    }
}
