//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_software()
        {
            this.tb_chave = new HashSet<tb_chave>();
        }
    
        public int cdSoftware { get; set; }
        public string software { get; set; }
        public int cdFabricante { get; set; }
        public int deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_chave> tb_chave { get; set; }
        public virtual tb_fabricante tb_fabricante { get; set; }
    }
}
